# Generated by Django 5.0.2 on 2024-03-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('work_id', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=35)),
                ('shift', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'workers',
            },
        ),
    ]
