# Generated by Django 5.0.2 on 2024-03-08 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Worker',
            new_name='Employee',
        ),
    ]
